apiVersion: v1
kind: Service
metadata:
  name: pcms-platformnpservice-srv
spec:
  type: NodePort
  selector:
    app: pcms-platformservice
  ports:
    - name: pcms-platformservice
      protocol: TCP
      port: 81
      targetPort: 81